name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      id: Install_dependencies
      if: ${{ always() }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with Wemake-Python-Styleguide
      id: Lint_Wemake-Python-Styleguide
      if: ${{ always() }}
      run: |
        flake8 . --count --statistics --format=html --htmldir=flake-report

    - name: Test with mypy
      id: Test_mypy
      if: ${{ always() }}
      run: |
        mypy . --explicit-package-bases

    - name: Telegram notification
      if: ${{ failure() }}
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Repository: ${{ github.repository }}

          Created commit: ${{ github.actor }}  

          Pipeline for branch ${{ github.head_ref }} commit ${{ github.event.pull_request.head.sha }} finished WITH ERROR

          Tested with Python ${{ matrix.python-version }}
          
          Steps details - ${{ toJson(steps) }}
            
          See changes: 
          https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/files
          
          https://github.com/${{ github.repository }}/commit/${{github.sha}}

    - name: Telegram notification
      if: ${{ success() }}
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Repository: ${{ github.repository }}

          Created commit: ${{ github.actor }}  

          Pipeline for branch ${{ github.head_ref }} commit ${{ github.event.pull_request.head.sha }} finished SUCCESSFULLY

          Tested with Python ${{ matrix.python-version }}
          
          See changes: 
          https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/files
          
          https://github.com/${{ github.repository }}/commit/${{github.sha}}
